---
title: "Lab 2"
date: January 30, 2022
author: Amy, Ksenia, and Rebecca
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE)

#install.packages("fivethirtyeight")
#remotes::install_github("fivethirtyeightdata/fivethirtyeightdata")
library(fivethirtyeight)
library(fivethirtyeightdata)
library(tidyverse)
library(lubridate)

```

```{r google-trends}
trends <- google_trends

##1.Start with the google trends data.
#Visualize the change in trends for each hurricane over time in one plot with three scales. Map color to a discrete scale.

trends$date <- ymd(trends$date)

trends_pivot <- trends %>% 
	pivot_longer(
		cols = starts_with("hurricane"),
		names_to = c("Hurricane", "name"),
		values_to = "n",
		names_sep = "_",
		values_drop_na = TRUE,
		names_repair = "check_unique",
		names_prefix = "hurricane_"
	) 

ggplot(trends_pivot,aes(date, n)) +
	geom_line(aes(color = Hurricane), alpha = .5, size = 2) +
	scale_color_brewer(palette = "Dark2") +
	theme_minimal() 

ggplot(trends_pivot,aes(date, n)) +
	geom_line(aes(color = Hurricane), alpha = .5, size = 2) +
	scale_color_brewer(palette = "Dark1") +
	theme_minimal() 

ggplot(trends_pivot,aes(date, n)) +	
	geom_line(aes(color = Hurricane), alpha = .5, size = 2) +
	scale_color_discrete() +
	theme_minimal()

#Visualize the trends again, this time with solid shapes (if your first plot was already solid shapes, use lines). Hint, geom_area can be difficult to work with if you have a grouping factor. Try geom_ribbon instead.

ggplot(trends_pivot, aes(x = date, y = n)) +
	geom_ribbon(aes(x = date, y = n, ymin = n - 1, ymax = n + 1, fill = Hurricane, color = Hurricane, linetype = Hurricane)) +
	geom_area(aes(fill = Hurricane)) +
	theme_minimal()
	

#Visualize the same relation, but change the scales so color is mapped to a continuous scale (the other scales should be discrete).

ggplot(trends_pivot, aes(x = date, y = Hurricane, fill = n)) +
	geom_tile() +
	scale_fill_continuous(type = "viridis") 

#Create a data frame (using tibble() or data.frame()) that includes the dates that each hurricane made landfall. Annotate one of your first two plots to include these reference points with vertical lines (Hint: use geom_vline(), specifying the data source for this layer as this new dataset). You do not have to include text annotations - just the vertical lines, but if you would like to try, look into geom_text() or geom_label(). 

landfall <- tibble(Hurricane = c("Harvey", "Irma", "Jose", "Maria"), Date = c("August 25, 2017", "September 10, 2017", "Did not make landfall", "September 20, 2017" ), numdate = c("2017-8-25", "2017-9-10", "NA", "2017-9-20"))


ggplot(trends_pivot, aes(date, Hurricane, fill = n)) +
	geom_tile(aes(date, Hurricane)) + 
  geom_vline(aes(xintercept = numdate, color = Hurricane), 
    data = landfall, alpha = 0.8)


geom_label(data = landfall, aes(x = numdate, y = Hurricane, label = landfall), 
           color = "orange", 
           size = 7, angle = 45, fontface = "bold")


  geom_line(aes(date, unemploy)) + 
  scale_fill_manual(values = c("blue", "red")) +
  xlab("date") + 
  ylab("unemployment")
```

```{r}
# Didn't include Jose b/c no reference line is needed since it didn't make landfall

landfall2 <- tibble(Hurricane = c("Harvey", 
                                  "Irma", 
                                  "Maria"), 
                    Date = c("August 25, 2017", 
                             "September 10, 2017", 
                             "September 20, 2017"), 
                    numdate = c("2017-08-25", 
                                "2017-09-10", 
                                "2017-09-20"))

# Overlaid vertical reference lines on top of the filled line graph (directions say to use one of the first two graphs)

ggplot(trends_pivot, 
       aes(x = date, 
           y = n)) +
	geom_ribbon(aes(x = date, 
	                y = n, 
	                ymin = n - 1, 
	                ymax = n + 1, 
	                fill = Hurricane, 
	                color = Hurricane, 
	                linetype = Hurricane)) +
	geom_area(aes(fill = Hurricane)) +
	theme_minimal() +
  geom_vline(aes(xintercept = ymd(numdate)), 
             data = landfall2, 
             lty = 2,
             alpha = 0.4)  


# Added labels to vertical reference lines
ggplot(trends_pivot, 
       aes(x = date, 
           y = n)) +
	geom_ribbon(aes(x = date, 
	                y = n, 
	                ymin = n - 1, 
	                ymax = n + 1, 
	                fill = Hurricane, 
	                color = Hurricane, 
	                linetype = Hurricane)) +
	geom_area(aes(fill = Hurricane)) +
	theme_minimal() +
  scale_y_continuous(expand = c(0,0)) + 
  labs(x = "Date", 
       y = "Google Search Interest") +
  geom_vline(aes(xintercept = ymd(numdate)), 
             data = landfall2, 
             lty = 2,
             alpha = 0.4) +
  geom_label(data = landfall2, 
             aes(x = ymd(numdate), 
                 y = 75, 
                 label = c("Harvey
 Landfall 
 Aug. 25", 
                           "Irma 
 Landfall
 Sep. 10", 
                           "Maria 
 Landfall
 Sep. 20")), 
           color = "gray50",
           size = 2.5)
```

